CREATE TABLE ENTITY (
	ENTITY_ID INT,
	TYPE INT,
	PRIMARY KEY (ENTITY_ID)
);
CREATE TABLE ENTITY_NAME (
	ENTITY_ID INT,
	NAME TEXT,
	PRIMARY KEY (ENTITY_ID)
);
CREATE TABLE ENTITY_INTERSECTION (
	CHILD_ENTITY_ID INT,
	PARENT_ENTITY_ID INT,
	PRIMARY KEY (CHILD_ENTITY_ID),
	FOREIGN KEY (CHILD_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID),
	FOREIGN KEY (PARENT_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID)
);
CREATE TABLE ENTITY_UNION (
	CHILD_ENTITY_ID INT,
	PARENT_ENTITY_ID INT,
	PRIMARY KEY (CHILD_ENTITY_ID),
	FOREIGN KEY (CHILD_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID),
	FOREIGN KEY (PARENT_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID)
);
CREATE TABLE ATTRIBUTION (
	CHILD_ENTITY_ID INT,
	PARENT_ENTITY_ID INT,
	INDEX INT,
	PRIMARY KEY (CHILD_ENTITY_ID),
	FOREIGN KEY (CHILD_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID),
	FOREIGN KEY (PARENT_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID)
);
CREATE TABLE INHERITANCE (
	CHILD_ENTITY_ID INT,
	PARENT_ENTITY_ID INT,
	PRIMARY KEY (CHILD_ENTITY_ID),
	FOREIGN KEY (CHILD_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID),
	FOREIGN KEY (PARENT_ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID)
);
CREATE TABLE ARGUMENT (
	ENTITY_ID INT,
	INDEX INT,
	TYPE INT,
	PRIMARY KEY (ENTITY_ID,INDEX),
	FOREIGN KEY (ENTITY_ID)
		REFERENCES ENTITY(ENTITY_ID)
);
CREATE TABLE ARGUMENT_NAME (
	ENTITY_ID INT,
	INDEX INT,
	NAME TEXT,
	TYPE INT,
	DEFAULTED BOOL,
	PRIMARY KEY (ENTITY_ID,INDEX),
	FOREIGN KEY (ENTITY_ID,INDEX)
		REFERENCES ARGUMENT(ENTITY_ID,INDEX)
);
CREATE TABLE ARGUMENT_CONDITION (
	ENTITY_ID INT,
	INDEX INT,
	CONDITION_TYPE INT,
	OTHER_ENTITY_ID INT,
	PRIMARY KEY (ENTITY_ID,INDEX,CONDITION_TYPE),
	FOREIGN KEY (ENTITY_ID,INDEX)
		REFERENCES ARGUMENT(ENTITY_ID,INDEX),
	FOREIGN KEY (OTHER_ENTITY_ID)
		REFERENCES ENTITY(OTHER_ENTITY_ID)
);